apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gocd-badges
  labels:
    name: gocd-badges
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gocd-badges
  template:
    metadata:
      labels:
        name: gocd-badges
        version: v1
    spec:
      containers:
      - name: gocd-badges
        image: "paulkane:1.0-SNAPSHOT"
        env:
        - name: JAVA_OPTS
          value: "-Xmx100G -Xmx100G"
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 250Mi
          limits:
            memory: 5Gi